-- ============================================================================
-- SUPERSEDED — do not run.
--
-- This single-file schema has been replaced by ordered migrations in
--   supabase/migrations/
-- (see supabase/README.md).
--
-- The old file could not rebuild the database: it defined tables but none of
-- the triggers, functions, or views the application actually depends on
-- (packaging live-stock updates, procurement balance updates, the
-- leaderboard_weekly view, updated_at maintenance, and profile auto-creation
-- on signup). It also carried heavy table redundancy that the new schema
-- consolidates. Kept here only as a historical reference pointer.
-- ============================================================================
